name: Commit & PR Logger

on:
  push:
    branches:
      #- main
      '**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  log-commit-or-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log info (commit or PR)
        run: |
          DATE=$(TZ="Asia/Jerusalem" date '+%Y-%m-%d %H:%M:%S')

          if [ "${{ github.event_name }}" == "push" ]; then
            AUTHOR=$(git log -1 --pretty=format:'%an')
            MESSAGE=$(git log -1 --pretty=format:'%s')
            echo "[$DATE] $AUTHOR - $MESSAGE" >> commit_log.txt

          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            PR_NUMBER=${{ github.event.pull_request.number }}
            PR_USER=${{ github.event.pull_request.user.login }}
            PR_STATE=${{ github.event.pull_request.mergeable_state }}

            if [ "$PR_STATE" == "dirty" ]; then
              echo "[$DATE] PR Check - Conflict detected in PR #$PR_NUMBER by $PR_USER" >> commit_log.txt
              echo "Conflict detected in PR #$PR_NUMBER"
              exit 1
            else
              echo "[$DATE] PR Check - No conflicts in PR #$PR_NUMBER by $PR_USER" >> commit_log.txt
              echo "No conflicts in PR #$PR_NUMBER"
            fi
          fi

      - name: Commit and push log
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add commit_log.txt
          git commit -m "Update commit log" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
